concerns-votable
abozhiy/TN_Sample_App pull request #7
Opened 2016-09-14 16:43 UTC by abozhiy

2016-09-17 09:52 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-<%= @answer.id %>').replaceWith(@votes.rating);
В ассетах нет erb и нет доступа к переменным из контроллера. Это же код, который работает на клиенте (в браузере) и работает уже после того, как сервер отправит ответ. Так что он знать не знает ничего о сервере и о его переменных, тем более, что их уже и нет.

2016-09-17 09:53 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      @votable.set_vote_down(current_user)
В vote_up ты делаешь `render json: @votable`, а здесь ничего не делаешь, поэтому и данных никаких нет.

2016-09-17 10:46 UTC, belinskidima requested changes

2016-09-17 10:46 UTC, belinskidima commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-<%= @answer.id %>').replaceWith(@votes.rating);
`@answer` - у тебя здесь нету, все данные ты парсишь из Json переданный xhr.
[Тут](https://github.com/abozhiy/TN_Sample_App/blob/concerns-votable/app/controllers/concerns/voted.rb#L12) ты правильно начал, но лучше передавать только нужные параметры. На пример

```
  def vote_up
    if !current_user.author_of?(@votable) && !current_user.voted?(@votable)
      @votable.set_vote_up(current_user)
      render json: { id: @votable.id, type: @votable.type, rating: @votable.rating, votes_count: @votable.votes_count }
    end
  end
```

Теперь ты в своем скрипте можешь принимать из джсона эти параметры и с ними делать что нужно.

```
$('.vote_up_answer-link').bind 'ajax:success', (e, data, status, xhr) ->
    vote = $.parseJSON(xhr.responseText);
    id = vote.id
    type = vote.type
    rating = vote.rating
    votes_count = vote.votes_count
```

2016-09-17 11:20 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-<%= @answer.id %>').replaceWith(@votes.rating);
а в случае с method: :delete и .destroy в методе контроллера, что будет возвращаться из джсона?

2016-09-17 11:34 UTC, airwall commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-<%= @answer.id %>').replaceWith(@votes.rating);
В нашем случае метод delete  не нужен. Но раз уж спрашиваешь то метод контроллера передаст то что ты укажешь, будь то json, js или html.

Попробую объяснить как я понимаю путь джсона до твоего скрипта.
В контроллере мы задаем параметры которые передаем на сторону клиента (браузера) таким образом: `render json: {message: "answer #{@answer.id} was destroyed" }`. 
Теперь когда наш экшен сработает, на пример Answer#destroy то контроллер передаст параметры клиенту `{message: "answer 1 was destroyed" }` это можно посмотреть в консоле браузера.

2016-09-17 11:51 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-<%= @answer.id %>').replaceWith(@votes.rating);
Примерно понял, но пока не понятно как привязывать скрипт к тому, что возвращает джсон. Т.е. к тому что мы передали в джсон, например тот же message: "answer 1 was destroyed".

А почему метод delete не нужен? я ведь собираюсь удалить голос, при нажатии cancel, после чего я так понимаю нужно отрендерить рейтинг со значением 0.

2016-09-17 11:52 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-<%= @answer.id %>').replaceWith(@votes.rating);
ладно, буду сидеть дальше разбираться)

2016-09-18 15:40 UTC, airwall commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
[Потому](http://connect.thinknetica.com/t/anton-bozhij-abozhiy/3083/79?u=belinski_d) что ты не правильно его выводишь.
`votes_cunt` если все правильно, а вроде ты его передал в контроллере, выводится так: `vote.votes_count`
попробуй написать тут `console.log(vote)` и понажимай на кнопку `vote up` посмотри что у тебя в консоли появляется.

2016-09-18 15:40 UTC, belinskidima approved these changes

2016-09-18 15:52 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
vote.votes_count так пробовал, тоже не рендерится.
Сейчас попробую с console.log(vote)

2016-09-18 15:55 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
в консоли выводит два раза Object {votes_count: 1}

2016-09-18 15:57 UTC, airwall commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
конечно он не будет рендерится, ведь куда ты его пытаешся вставить? В ` $('.rating-answer-')` а где это у еас? Такого у нас нема. У нас есть `"rating-answer-#{answer.id}"` то есть тепе из еонтроллера надо передать и `id` что бы тут указать его. [Здесь](https://github.com/abozhiy/TN_Sample_App/blob/concerns-votable/app/controllers/concerns/voted.rb#L13) ты должен по мимо `votes_count` передать и `id`.
```
render json: { votes_count: @votable.votes_count, id: @votable.id }
```
И вот сейчас мы можем указать правильно куда нам вставлять новое значение
```
$('.rating-answer-' + vote.id ).replaceWith('Rating: ' + vote.votes_count);
```

2016-09-18 15:59 UTC, airwall commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
Все правильно, в консоли тебе показывает `vote` - это тот json который ты передаешь из контроллера.

2016-09-18 16:08 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
получилось, спасибо

2016-09-18 20:38 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
Дим, подскажи пжл, возможно ли привязать условием ссылку cancel к тому что возвращается клиентом, я вот пытаюсь сделать следующим образом, но это не работает:

> $('.vote_up_answer-link').bind 'ajax:success', (e, data, status, xhr) ->
>     vote = $.parseJSON(xhr.responseText);
>     $('.rating-answer-' + vote.id).replaceWith('Rating: ' + vote.votes_count);
>     if(vote.votes_count != 0)
>       $('.vote_cancel_answer-link' + vote.id).replaceWith('Rating: ' + vote.votes_count);

правильно ли так вообще?

2016-09-18 21:37 UTC, airwall commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
Я так понимаю, ты хочешь сделать активную кнопку cancel после голосования. 
Я вижу два варианта в твоем случае, это отрендерить тут html с ссылкой на отмену голосования, но будет выглядеть не красиво.
Или в `views/answers/_answer.html.slim` не прятать всю ссылку `cancel` с условием `- if current_user.voted?(answer)` а задавать ссылке скрытый класс что позволит ее показать потом. Ща распишу второй вариант.

```
  $('.vote_up_answer-link').bind 'ajax:success', (e, data, status, xhr) ->
    vote = $.parseJSON(xhr.responseText);
    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
    $('.voting-for-answer-' + vote.id ' #cancel_vote).toggleClass('vote_cancel_answer-link')
```
`views/answers/_answer.html.slim`
```
    div class="voting-for-answer-#{answer.id}"
      span class="rating-answer-#{answer.id}" Rating: #{answer.votes_count}
      - if user_signed_in? && !current_user.author_of?(answer)
        | &emsp;
        span= link_to '+', vote_up_answer_path(answer), method: :patch, remote: true, data: { type: :json }, class: 'vote_up_answer-link'
        | &emsp;
        span= link_to '-', vote_down_answer_path(answer), method: :patch, remote: true, data: { type: :json }, class: 'vote_down_answer-link'
          | &emsp;
          span= link_to 'Cancel', vote_cancel_answer_path(answer), method: :delete, remote: true, data: { type: :json }, class: "#{current_user.voted?(answer) ? 'vote_cancel_answer-link' : 'hidden'"
```
и такой css:
```
.hidden{
  display: none;
  }
```

Теперь твоя ссылка отображается на странице только если пользователь уже проголосовал, разница с предыдущим вариантом только в том что сама ссылка в html коде есть, она не отображается на странице и это нам позволит в скрипте изменить ей класс и показать после голосования.

2016-09-18 21:51 UTC, airwall commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
А еще, ты можешь из контроллера прислать скрипту статус голосования `voted: true/false` и на основе этого отображать нужные ссылки.

2016-09-18 23:23 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
как просто оказывается

2016-09-18 23:47 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
но пока что не работает)
поигрался с отступами перед:
`span= link_to 'Cancel', vote_cancel_answer_path(answer), method: :delete, remote: true, data: { type: :json }, class: "#{current_user.voted?(answer) ? 'vote_cancel_answer-link' : 'hidden'}", id: "cancel_vote"`

но нивкакую

2016-09-18 23:58 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
и такая вот ошибка:

> 10) Vote for answer 
>   In order to vote for answer
>   As an autenticated user
>   I want to be able to voit for answer
>  Not-authenticated user
>       Failure/Error: i= link_to 'Cancel', vote_cancel_question_path(question), method: :delete, remote: true, data: { type: :json }, class: "#{current_user.voted?(question) ? 'vote_cancel_question-link' : 'hidden'}", id: "cancel_vote"
>       
>       ActionView::Template::Error:
>         undefined method `voted?' for nil:NilClass
>       # ./app/views/questions/_question.html.slim:13:in `_app_views_questions__question_html_slim___2299311292820512847_70179177509280'

2016-09-19 10:05 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
Внимательно посмотри сообщение об ошибке и свой код:  undefined method `voted?' for **nil:NilClass**. То есть, ты вызываешь метод `voted? ` у объекта, в котором nil. Смотрим код, где вызывается `voted?` в этой строке? Вот здесь: `class: "#{current_user.voted?(question) ? 'vote_cancel_question-link' : 'hidden'}"`. Выходит, что current_user возвращает nil. В каком случае это возможно? Если юзер не залогинен. 

Два вывода:

 - В тесте, похоже, юзер не залогинен
 - Нужно предусмотреть это во вьюхе и если юзер не залогинен, прятать от него ссылку.

2016-09-19 10:07 UTC, vkurennov commented on app/models/user.rb
> +    object.votes.where(user: self).exists?
Проще так: `votes.where(votable:object).exists?`. Ты же у юзера вызываешь метод, вот и работай через его ассоциации, а не через ассоциации переданного объекта

2016-09-19 10:07 UTC, vkurennov requested changes

2016-09-19 13:31 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
поправил... Что-то пока не получается нормально запустить ссылку cancel

Ребят, подскажите, что еще может означать ошибка в консоли:
Uncaught TypeError: vote.id is not a function

![2016-09-19 16 28 31](https://cloud.githubusercontent.com/assets/20154523/18633697/3da716ea-7e86-11e6-9c75-1450b5ac4787.png)

2016-09-19 13:37 UTC, airwall commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
Ну там же пишет что не так. Должно быть `.. vote.id + '#cancel_vote').toggle...`  а у тебя скорее всего  `.. vote.id('#cancel_vote').toggle...`  что не верно.

2016-09-19 13:40 UTC, abozhiy commented on app/assets/javascripts/answers.coffee
> +    $('.rating-answer-').replaceWith('Rating: ' + votes_count);
понял

2016-09-19 13:45 UTC, airwall commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
Тут пробел важен, может поэтому и выскакивает та ошибка.
```
+ vote.id ' #cancel_vote').toggl
```

2016-09-19 13:55 UTC, abozhiy commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
С пробелом как раз была ошибка, сейчас заменил на +
Пока что не работает, но ошибки в консоли больше нет.

2016-09-19 13:57 UTC, abozhiy commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
а вот тут: `toggleClass('vote_cancel_question-link');` нужна точка(класс) перед 

`vote_cancel_question-link`?

2016-09-19 13:58 UTC, airwall commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
да, конечно. Я даже не обратил внимание на то что она отсутствует.

2016-09-19 13:58 UTC, airwall commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
Нет, кажется нет. http://api.jquery.com/toggleclass/

2016-09-19 14:51 UTC, abozhiy commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
как еще можно вычислить, почему не отображается ссылка, если в консоли ошибок нет, спеки ругаются только на отсутствие этой ссылки, а статус везде 200?)

2016-09-19 14:55 UTC, airwall commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
Используй `console.log` сначало введи туда `console.log($('.voting-for-question-' + vote.id +  '#cancel_vote'))`, посмотри правильно ли все там и соответствует ли все с тем что у тебя в HTML. Если json до скрипта доходит то дальше проблема только в верстке.

2016-09-19 14:57 UTC, belinskidima commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
попробуй может переделать селекторы, понятней, привяжи к каждой ссылке уникальный айди и в скрипте используй его.

2016-09-19 15:51 UTC, airwall commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
В консоли должен вернутся объект указывающий на ссылку с id #cancel_vote
http://joxi.ru/brR5PdaTQgBlpA.jpg

2016-09-19 16:21 UTC, abozhiy commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
В моем случае объект возвращается, но без ссылки, следовательно джсон до скрипта не доходит, так? И все дело видимо в селекторе?
![2016-09-19 19 12 14](https://cloud.githubusercontent.com/assets/20154523/18639827/245e5122-7e9e-11e6-80ab-c4b5beb2a657.png)

2016-09-20 10:43 UTC, abozhiy commented on app/assets/javascripts/questions.coffee
> +    $('.voting-for-question-' + vote.id '#cancel_vote').toggleClass('vote_cancel_question-link');
А может дело быть в методе .toggleClass? Ведь этот метод добавляет класс, если его нет, а если есть удаляет. Но на странице же уже висит класс hidden, который после голосования становится тем классом, который мы и пытаемся добавить методом.

2016-09-20 18:05 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +    $('.cancel-vote-' + vote.id + '#cancel_vote').toggleClass('vote_cancel_answer-link');
Я что-то не понимаю, где у тебя вообще есть класс вида `.cancel-vote-1`? вижу только `vote_cancel_answer-link` и аналогичный для ответа.

2016-09-20 18:06 UTC, vkurennov requested changes
Пока не стал подробно проверять, и так видно что с селекторами какая-то каша.

2016-09-21 19:13 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +    $('#cancel_vote-' + vote.id + '.hidden').toggleClass('hidden');
Можно было в одну цепочку объеденить: `$('#cancel_vote-' + vote.id).toggleClass('hidden').addClass('vote_cancel_answer-link')`

2016-09-21 19:14 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      unless current_user.voted?(@votable)
Объедени условия в одно составное, зачем плодить вложенные условия? И т.к. условие составное, то замени на if, так проще

2016-09-21 19:14 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      unless current_user.voted?(@votable)
Замени на if с составным условием

2016-09-21 19:15 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +      @votable.set_vote_cancel(current_user)
А зачем в названии метода set? Лучше ведь назвать просто `cancel_vote`

2016-09-21 19:23 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def set_vote_up(user)
Назови метод просто vote_up

2016-09-21 19:23 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def set_vote_down(user)
А этот - vote_down

2016-09-21 19:23 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def set_vote_cancel(user)
cancel_vote

2016-09-21 19:25 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  extend ActiveSupport::Concern
А где тесты на все методы в этом консерне? Имею в виду тесты моделей (юнит-тесты)?

2016-09-21 19:25 UTC, vkurennov commented on app/models/user.rb
> +  def voted?(object)
И на этот метод нужен тест в модели

2016-09-21 19:25 UTC, vkurennov requested changes
Нужны тесты и небольшой рефакторинг

2016-09-22 09:42 UTC, palkan commented on app/models/user.rb
> +  def voted?(object)
А лучше будет перенести этот метод в конcерн `Votable` и вызывать, наоборот, от голосуемого объекта (`answer.voted_by?(user)`).
Этот метод для самого пользователя не имеет смысла, только в контексте голосования, так лучше и добавлять его в соответствующем месте.

2016-09-22 11:02 UTC, merged