comet-pub-sub
abozhiy/TN_Sample_App pull request #8
Opened 2016-09-22 11:48 UTC by abozhiy

2016-09-27 15:44 UTC, vkurennov requested changes
Исправь замечания

2016-09-27 15:44 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +        format.js do
Если у тебя только format.js, то зачем вообще делать respond_to? Он нужен, когда одновременно несколько форматов поддерживается

2016-09-27 15:44 UTC, vkurennov commented on app/models/comment.rb
> +  belongs_to :commentable, polymorphic: true, optional: true
А почему optional? Разве может существовать комментарий сам по себе, без привязки к родительскому объекту?

2016-09-27 15:44 UTC, vkurennov commented on app/models/comment.rb
> +  validates :user_id, :commentable_id, :body, presence: true
commentable_id валидировать не стоит. Дело в том, что поля для полиморфных ассоциаций устанавливаются после валидации уже.

2016-09-27 15:44 UTC, vkurennov commented on app/assets/javascripts/comments.coffee
> +  PrivatePub.subscribe '/comments', (data, channel) ->
У тебя глобальный канал получается, т.е. не важно, на какой странице находится юзер, если он создал коммент, то все отсальные юзеры его получат. Другое дело, что они его не отобразат, но зачем вообще слать данные тому, кому они заведомо не нужны. Привяжи канал комментариев к id вопроса, все равно все происходит на странице вопроса, в т.ч. создаются комменты к ответам

2016-09-27 15:44 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    = subscribe_to "/answers/#{@answer.id}/comments"
У тебя же нет такого канала, зачем на него подписываться?

2016-09-27 15:44 UTC, vkurennov commented on app/views/answers/create.js.erb
> +    $('#answers_count').text('<%= j pluralize(@answer.question.answers.count, 'Answer') %>');
У тебя же здесь загружена переменная @question, вот через нее и обращайся.

2016-09-27 15:44 UTC, vkurennov commented on app/views/comments/_comment.html.slim
> +- commentable.comments.each do |comment|
Если выводишь спсиок, называй паршл во множественном числе

2016-09-27 15:44 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +  = subscribe_to "/questions/#{@question.id}/comments"
А вот этот канал как раз пригодится, но сейчас у тебя есть только глобальный канал /comments

2016-09-27 15:44 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = subscribe_to "/questions/#{@question.id}/answers"
Собственно, все subscribe_to нужно написать здесь. Вызов этого метода должен быть 1 раз на страницу для каждого канала.

2016-09-27 15:44 UTC, vkurennov commented on spec/factories/comments.rb
> +    user_id 1
Не связывай фабрики по id, это боком выйдет, когда такого id не окажется в базе или еще что-нибудь такое случится. Замаешься отлаживать тесты. Используй ассоциации:

  ```
factory :comment do
   body "MyText"
   user
   association :commenatble, factory: :question
 end
```

2016-09-27 20:51 UTC, abozhiy commented on app/controllers/comments_controller.rb
> +        format.js do
а как же тогда отрендерить и comment в json и js.erb с ошибками, тут же явно js с переменной связан, а если не будет переменной, что-то не соображу

2016-09-27 20:53 UTC, abozhiy commented on app/views/answers/_answer.html.slim
> +    = subscribe_to "/answers/#{@answer.id}/comments"
забыл удалить

2016-09-28 10:40 UTC, abozhiy commented on spec/factories/comments.rb
> +    user_id 1
но сразу падают тесты контроллера с вот такой ошибкой:
```
1) CommentsController POST #create Question comment Authenticated user tries to leave comment with valid attributes increase comment count by 1
     Failure/Error: let!(:question_comment) { create(:comment, commentable_type: question, user: user) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: User must exist, User can't be blank
```
Хотя юзер указан, не пойму в чем дело.

2016-09-28 10:46 UTC, abozhiy commented on app/models/comment.rb
> +  belongs_to :commentable, polymorphic: true, optional: true
Без optional все тесты контроллера падают с ошибкой:

```
10) CommentsController DELETE #destroy Answer comment Authenticated user cannot delete other comment
      Failure/Error: let!(:question_comment) { create(:comment, commentable_type: question, user: user) }
      
      NameError:
        wrong constant name #<Question:0x007fd4ca1f3320>
```

2016-09-28 12:17 UTC, merged